[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "millers-hollow"
version = "0.1.0"
dependencies = [
  "aiosqlite",
  "fastapi",
  "pydantic",
  "uvicorn",
  "openai",
]
requires-python = ">=3.10"
authors = [
  {name = "Moonshine4002", email = "moonshine2004@163.com"},
]
maintainers = [
  {name = "Moonshine4002", email = "moonshine2004@163.com"},
]
description = "AI-powered simulation of The Werewolves of Miller's Hollow social deduction game"
readme = "README.md"
license = { text = "MIT" }
license-files = ["LICEN[CS]E*"]
keywords = ["Game", "AIGC", "RESTful", "Database"]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Programming Language :: Python",
]

[project.optional-dependencies]
gui = [
  "PySide6",
  "httpx",
]
dev = [
  "build",
  "mypy",
  "blue",
]
build-exe = [
  "nuitka",
  "hatch",
]

[project.urls]
Homepage = "https://example.com"
Documentation = "https://github.com/Moonshine4002/millers-hollow/wiki"
Repository = "https://github.com/Moonshine4002/millers-hollow.git"
"Bug Tracker" = "https://github.com/Moonshine4002/millers-hollow/issues"
Changelog = "https://github.com/Moonshine4002/millers-hollow/blob/main/CHANGELOG.md"

[project.scripts]
millers-server = "millers_hollow.server:run_server"

[project.gui-scripts]
millers-client = "millers_hollow.client:run_client"

[tool.hatch.envs.build-exe]
features = ["gui"]
dependencies = [
  "nuitka",
  "pyinstaller",
]

scripts.build-server = "hatch run build-exe:build-nuitka-server"
scripts.build-client = "hatch run build-exe:build-nuitka-client"

scripts.build-nuitka-server = """python -m nuitka \
  --standalone \
  --onefile \
  --include-package=millers_hollow \
  --output-dir=nuitka \
  --output-filename=millers-server \
  server.py \
"""
scripts.build-nuitka-client = """python -m nuitka \
  --standalone \
  --onefile \
  --include-package=millers_hollow \
  --output-dir=nuitka \
  --output-filename=millers-client \
  --enable-plugin=pyside6 \
  --windows-console-mode=disable \
  client.py \
"""

scripts.build-pyinstaller-server = """pyinstaller \
  -F \
  --hidden-import=millers_hollow \
  --name=millers-server \
  --distpath=pyinstaller/dist \
  --workpath=pyinstaller/build \
  --specpath=pyinstaller \
  server.py \
"""
scripts.build-pyinstaller-client = """pyinstaller \
  -F \
  --hidden-import=millers_hollow \
  --name=millers-client \
  --distpath=pyinstaller/dist \
  --workpath=pyinstaller/build \
  --specpath=pyinstaller \
  --windowed \
  client.py \
"""
